ARG version
FROM almalinux:$version
#How can you check OS of your server? cat /etc/*release
ARG kakinada
ARG hyderabad
RUN echo "kakinada is $kakinada Hyderabad is $hyderabad "
CMD [ "sleep", "100" ]
