ARG version
FROM almalinux:${version:-8.8}
ARG venu=funnyboy
ARG sana=dumandduff
ENV train=BBSTPYExpress
RUN echo "venu is ${venu} and sana is ${sana} train is ${trian} "
CMD [ "sleep","100" ]
# How can you check the version of OS? cat /etc/*release
# Here :${version:-8.8} this syntax will be accessible when we use ARG in version
# this syntax will not be accessible if use ARG otherthan versions