name: expense
networks:
 default:
   name: jajikaya
volumes:
  lolipop:
  external: true

services:
   mysql:
     image: expense-database:v.10.0
     container_name: mysql
     volumes:
     - source: lolipop
       target: /var/lib/mysql
       type: volume
   backend:
     image: expense-backend:v.10.0
     container_name: backend
     command: sh -c "sleep 50 && node /opt/server/index.js"
     depends_on:
      - mysql
   frontend:
     image: expense-frontend:v.10.0
     container_name: frontend
     depends_on:
      - backend
     ports:
     - 80:80
