name: expense
networks:
  default:
   name: sundari

services:

  mysql:
    
    image: expense-database:v.10.0
    container_name: mysql

  backend:

    image: expense-backend:v.10.0
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - mysql
  
  frontend:
    image: expense-frontend:v.10.0
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend
    

